# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Istio

on: workflow_dispatch

env:
  SKIP_TEST: true
  ES_VERSION: es7
  TAG: ${{ github.sha }}
  SCRIPTS_DIR: test/e2e-mesh/e2e-istio/scripts
  NGE2E_DIR: test/nge2e/nge2efile
  SW_OAP_BASE_IMAGE: openjdk:11-jdk

jobs:
  metrics-service:
    runs-on: ubuntu-16.04
    timeout-minutes: 60
    name: Istio(${{ matrix.istio_version }})+MetricsService
    strategy:
      fail-fast: true
      matrix:
        istio_version: [1.9.1]
    env:
      ISTIO_VERSION: ${{ matrix.istio_version }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check Unintended Changes
        run: |
          echo "::group::Check sw.version"
          sudo apt install -y -q xmlstarlet
          SW_VERSION=$(xmlstarlet sel -N pom=http://maven.apache.org/POM/4.0.0 -t -v "/pom:project/pom:properties/pom:sw.version" test/e2e/pom.xml)
          if [[ "$(echo $(echo $SW_VERSION))" != "" ]]; then
            echo "Please don't submit the change of sw.version in test/e2e/pom.xml"
            exit 1
          fi
          echo "::endgroup::"

      - name: Set Skip Env Var
        uses: ./.github/actions/skip

      - uses: actions/cache@v2
        if: env.SKIP_CI != 'true'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-w

      - name: Build Docker Image
        if: env.SKIP_CI != 'true'
        run: make docker

      - name: Prepare environment
        if: env.SKIP_CI != 'true'
        run: bash ${SCRIPTS_DIR}/pre.sh

      - name: NGE2E
        if: env.SKIP_CI != 'true'
        run: e2e run -c ${NGE2E_DIR}/e2e.yaml
